# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/polta/Downloads/JJ_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/polta/Downloads/JJ_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/polta/Downloads/JJ_Project/CMakeFiles /mnt/c/Users/polta/Downloads/JJ_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/polta/Downloads/JJ_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Driver

# Build rule for target.
Driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Driver
.PHONY : Driver

# fast build rule for target.
Driver/fast:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/build
.PHONY : Driver/fast

#=============================================================================
# Target rules for targets named harness

# Build rule for target.
harness: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 harness
.PHONY : harness

# fast build rule for target.
harness/fast:
	$(MAKE) -f CMakeFiles/harness.dir/build.make CMakeFiles/harness.dir/build
.PHONY : harness/fast

#=============================================================================
# Target rules for targets named Part1

# Build rule for target.
Part1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Part1
.PHONY : Part1

# fast build rule for target.
Part1/fast:
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/build
.PHONY : Part1/fast

Driver.o: Driver.cpp.o

.PHONY : Driver.o

# target to build an object file
Driver.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/Driver.cpp.o
.PHONY : Driver.cpp.o

Driver.i: Driver.cpp.i

.PHONY : Driver.i

# target to preprocess a source file
Driver.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/Driver.cpp.i
.PHONY : Driver.cpp.i

Driver.s: Driver.cpp.s

.PHONY : Driver.s

# target to generate assembly for a file
Driver.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/Driver.cpp.s
.PHONY : Driver.cpp.s

harness.o: harness.cpp.o

.PHONY : harness.o

# target to build an object file
harness.cpp.o:
	$(MAKE) -f CMakeFiles/harness.dir/build.make CMakeFiles/harness.dir/harness.cpp.o
.PHONY : harness.cpp.o

harness.i: harness.cpp.i

.PHONY : harness.i

# target to preprocess a source file
harness.cpp.i:
	$(MAKE) -f CMakeFiles/harness.dir/build.make CMakeFiles/harness.dir/harness.cpp.i
.PHONY : harness.cpp.i

harness.s: harness.cpp.s

.PHONY : harness.s

# target to generate assembly for a file
harness.cpp.s:
	$(MAKE) -f CMakeFiles/harness.dir/build.make CMakeFiles/harness.dir/harness.cpp.s
.PHONY : harness.cpp.s

hashTable.o: hashTable.cpp.o

.PHONY : hashTable.o

# target to build an object file
hashTable.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/hashTable.cpp.o
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/hashTable.cpp.o
.PHONY : hashTable.cpp.o

hashTable.i: hashTable.cpp.i

.PHONY : hashTable.i

# target to preprocess a source file
hashTable.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/hashTable.cpp.i
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/hashTable.cpp.i
.PHONY : hashTable.cpp.i

hashTable.s: hashTable.cpp.s

.PHONY : hashTable.s

# target to generate assembly for a file
hashTable.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/hashTable.cpp.s
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/hashTable.cpp.s
.PHONY : hashTable.cpp.s

histogram.o: histogram.cpp.o

.PHONY : histogram.o

# target to build an object file
histogram.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/histogram.cpp.o
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/histogram.cpp.o
.PHONY : histogram.cpp.o

histogram.i: histogram.cpp.i

.PHONY : histogram.i

# target to preprocess a source file
histogram.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/histogram.cpp.i
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/histogram.cpp.i
.PHONY : histogram.cpp.i

histogram.s: histogram.cpp.s

.PHONY : histogram.s

# target to generate assembly for a file
histogram.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/histogram.cpp.s
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/histogram.cpp.s
.PHONY : histogram.cpp.s

join.o: join.cpp.o

.PHONY : join.o

# target to build an object file
join.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/join.cpp.o
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/join.cpp.o
.PHONY : join.cpp.o

join.i: join.cpp.i

.PHONY : join.i

# target to preprocess a source file
join.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/join.cpp.i
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/join.cpp.i
.PHONY : join.cpp.i

join.s: join.cpp.s

.PHONY : join.s

# target to generate assembly for a file
join.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/join.cpp.s
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/join.cpp.s
.PHONY : join.cpp.s

list.o: list.cpp.o

.PHONY : list.o

# target to build an object file
list.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/list.cpp.o
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/list.cpp.o
.PHONY : list.cpp.o

list.i: list.cpp.i

.PHONY : list.i

# target to preprocess a source file
list.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/list.cpp.i
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/list.cpp.i
.PHONY : list.cpp.i

list.s: list.cpp.s

.PHONY : list.s

# target to generate assembly for a file
list.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/list.cpp.s
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/list.cpp.s
.PHONY : list.cpp.s

parse_relation.o: parse_relation.cpp.o

.PHONY : parse_relation.o

# target to build an object file
parse_relation.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/parse_relation.cpp.o
.PHONY : parse_relation.cpp.o

parse_relation.i: parse_relation.cpp.i

.PHONY : parse_relation.i

# target to preprocess a source file
parse_relation.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/parse_relation.cpp.i
.PHONY : parse_relation.cpp.i

parse_relation.s: parse_relation.cpp.s

.PHONY : parse_relation.s

# target to generate assembly for a file
parse_relation.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/parse_relation.cpp.s
.PHONY : parse_relation.cpp.s

partitioner.o: partitioner.cpp.o

.PHONY : partitioner.o

# target to build an object file
partitioner.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/partitioner.cpp.o
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/partitioner.cpp.o
.PHONY : partitioner.cpp.o

partitioner.i: partitioner.cpp.i

.PHONY : partitioner.i

# target to preprocess a source file
partitioner.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/partitioner.cpp.i
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/partitioner.cpp.i
.PHONY : partitioner.cpp.i

partitioner.s: partitioner.cpp.s

.PHONY : partitioner.s

# target to generate assembly for a file
partitioner.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/partitioner.cpp.s
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/partitioner.cpp.s
.PHONY : partitioner.cpp.s

queryParser.o: queryParser.cpp.o

.PHONY : queryParser.o

# target to build an object file
queryParser.cpp.o:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/queryParser.cpp.o
.PHONY : queryParser.cpp.o

queryParser.i: queryParser.cpp.i

.PHONY : queryParser.i

# target to preprocess a source file
queryParser.cpp.i:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/queryParser.cpp.i
.PHONY : queryParser.cpp.i

queryParser.s: queryParser.cpp.s

.PHONY : queryParser.s

# target to generate assembly for a file
queryParser.cpp.s:
	$(MAKE) -f CMakeFiles/Driver.dir/build.make CMakeFiles/Driver.dir/queryParser.cpp.s
.PHONY : queryParser.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/Part1.dir/build.make CMakeFiles/Part1.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Driver"
	@echo "... harness"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Part1"
	@echo "... Driver.o"
	@echo "... Driver.i"
	@echo "... Driver.s"
	@echo "... harness.o"
	@echo "... harness.i"
	@echo "... harness.s"
	@echo "... hashTable.o"
	@echo "... hashTable.i"
	@echo "... hashTable.s"
	@echo "... histogram.o"
	@echo "... histogram.i"
	@echo "... histogram.s"
	@echo "... join.o"
	@echo "... join.i"
	@echo "... join.s"
	@echo "... list.o"
	@echo "... list.i"
	@echo "... list.s"
	@echo "... parse_relation.o"
	@echo "... parse_relation.i"
	@echo "... parse_relation.s"
	@echo "... partitioner.o"
	@echo "... partitioner.i"
	@echo "... partitioner.s"
	@echo "... queryParser.o"
	@echo "... queryParser.i"
	@echo "... queryParser.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

